apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - route-dashboard.yaml
  - networkpolicy-openshift.yaml

patches:
  - path: delete-ingress.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/headGroupSpec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/workerGroupSpecs/0/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/workerGroupSpecs/1/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: RayCluster
