apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: gym-config
  - patch: |-
      - op: replace
        path: /spec/workerGroupSpecs/1/template/spec/containers/0/env/2/value
        value: "python resources_servers/example_single_tool_call/app.py"
      - op: replace
        path: /spec/workerGroupSpecs/1/template/spec/containers/0/env/4/value
        value: "resources_instance"
    target:
      kind: RayCluster
      name: gym-ray
