apiVersion: v1
kind: Service
metadata:
  name: gym-resources-svc
  namespace: gym
  labels:
    app.kubernetes.io/name: gym-resources
    app.kubernetes.io/part-of: nemo-gym
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gym-resources
  ports:
    - port: 9080
      targetPort: http
      protocol: TCP
      name: http
